@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Fri Jun 05 22:24:29 +0530 2020
=======
REM Generated by Vivado on Thu Jun 04 22:30:49 +0530 2020
>>>>>>> 924285812bbfa5c47f6015c0188b195aa3c0da70
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim upd_parser_tb_behav -key {Behavioral:sim_1:Functional:upd_parser_tb} -tclbatch upd_parser_tb.tcl -view D:/Dev/ACCELR/Prj3-40g_UDP_Parser_design/40g-udp-parser-fsm/upd_parser_tb_behav.wcfg -log simulate.log"
call xsim  upd_parser_tb_behav -key {Behavioral:sim_1:Functional:upd_parser_tb} -tclbatch upd_parser_tb.tcl -view D:/Dev/ACCELR/Prj3-40g_UDP_Parser_design/40g-udp-parser-fsm/upd_parser_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
