webtalk_init -webtalk_dir D:/Dev/ACCELR/Prj3-40g_UDP_Parser_design/40g_UDP_Parser_v0.1/40g_UDP_Parser_v0.1.sim/sim_1/behav/xsim/xsim.dir/upd_parser_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun 10 05:58:23 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d308672f-380e-4f30-aa18-72a277a4dd12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "50a3779a77964c66a3540a532e725e75" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "105" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "3" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "106 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "4 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "25" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "49316_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1706101671 -regid "" -xml D:/Dev/ACCELR/Prj3-40g_UDP_Parser_design/40g_UDP_Parser_v0.1/40g_UDP_Parser_v0.1.sim/sim_1/behav/xsim/xsim.dir/upd_parser_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Dev/ACCELR/Prj3-40g_UDP_Parser_design/40g_UDP_Parser_v0.1/40g_UDP_Parser_v0.1.sim/sim_1/behav/xsim/xsim.dir/upd_parser_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Dev/ACCELR/Prj3-40g_UDP_Parser_design/40g_UDP_Parser_v0.1/40g_UDP_Parser_v0.1.sim/sim_1/behav/xsim/xsim.dir/upd_parser_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
